spring.application.name=padelplay-cliente
server.port=8081
server.api.url=http://localhost:8080
google.client-id=75813445817-4rvtubv93v7tcc3h7o3t8tu5s8u4tbsn.apps.googleusercontent.com
spring.thymeleaf.cache=false
