spring.application.name=padelplay-server
server.port=8080

# =========================
# H2 DATABASE (temporal)
# =========================
spring.datasource.url=jdbc:h2:mem:padelplaydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=padel

# =========================
# JPA / Hibernate
# =========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# Consola H2
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false

# =========================
# Google OAuth
# =========================
google.client-id=75813445817-4rvtubv93v7tcc3h7o3t8tu5s8u4tbsn.apps.googleusercontent.com

# =========================
# JWT Configuration
# =========================
jwt.secret=padelplay-super-secret-key-que-debe-tener-minimo-256-bits-para-hs256
jwt.expiration=86400000