spring.application.name=padelplay-server
server.port=8080

# =========================
# H2 DATABASE (temporal)
# =========================
spring.datasource.url=jdbc:h2:mem:padelplaydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=padel

# =========================
# JPA / Hibernate
# =========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# Consola H2
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console